### PR TITLE
URL2SGSI

### PR DESCRIPTION
**Pull request by rahulkhatri137**
Only Generic Supported 🙂

### CODE REVIEW

**Review by xiaoxindada — CHANGES_REQUESTED** [review]
Thank you for providing this idea for this tool
However, there seems to be the following problems:
1. The copyright of the original author of url2sgsi script base change and the author of rebase change
2. This script should keep all the contents of sgsi output, not just a system.img, which destroys the integrity of sgsi
3. In fact, you can support any ROM type, just one more args

**Comment by yiesko** [comment]
Some lines of code are from stck-lzm, TrebleExperience, Erfan Abdi.

**Comment by xiaoxindada** [comment]
OK, but still need to mark the copyright, which is a respect for everyone

**Comment by yiesko** [comment]
I know, just told the authors

**Pull request closed without merging**
