### PR TITLE
Fix (#34) packing error introduced in PR #33

### PR DESCRIPTION
**Pull request by FanBB2333**
I just temporarily change the path back to the original one and test the existence of the directory in advance, also I fixed a typo and optimize `press any key`. Details are listed in commit messages.

### CODE REVIEW

**Comment by rahulkhatri137** [comment]
But there is no system var!

**Comment by FanBB2333** [comment]
> But there is no system var!

So there needs modification for the config file, otherwise, the packing procedure cannot be done.

**Comment by rahulkhatri137** [comment]
> > But there is no system var!
> 
> So there needs modification for the config file, otherwise, the packing procedure cannot be done.

Did you actually check what's error while packing image?
#33 was actually correct to fix files copy to system!
It should actually be system contexts & fs config that still has old files data not problem from new ones

**Comment by FanBB2333** [comment]
> > > But there is no system var!
> > 
> > 
> > So there needs modification for the config file, otherwise, the packing procedure cannot be done.
> 
> Did you actually check what's error while packing image? #33 was actually correct to fix files copy to system! It should actually be system contexts & fs config that still has old files data not problem from new ones

Thanks! I am going to check them later.

**Comment by xiaoxindada** [comment]
> > > > But there is no system var!
> > > 
> > > 
> > > So there needs modification for the config file, otherwise, the packing procedure cannot be done.
> > 
> > 
> > Did you actually check what's error while packing image? #33 was actually correct to fix files copy to system! It should actually be system contexts & fs config that still has old files data not problem from new ones
> 
> Thanks! I am going to check them later.

#33 Need to patch FS & contexts on repackage config file while success moving files

**Comment by FanBB2333** [comment]
> > > > > But there is no system var!
> > > > 
> > > > 
> > > > So there needs modification for the config file, otherwise, the packing procedure cannot be done.
> > > 
> > > 
> > > Did you actually check what's error while packing image? #33 was actually correct to fix files copy to system! It should actually be system contexts & fs config that still has old files data not problem from new ones
> > 
> > 
> > Thanks! I am going to check them later.
> 
> #33 Need to patch FS & contexts on repackage config file while success moving files

That's right! Thanks!

**Pull request merged**
